# Generated by Django 5.0.6 on 2024-06-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0002_operation_address_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='citizen_identification',
        ),
    ]
