# Generated by Django 5.0.6 on 2024-06-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0007_machineparameter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineparameter',
            name='max_value',
            field=models.FloatField(null=True),
        ),
    ]
