# Generated by Django 5.0.6 on 2024-06-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0008_machineparameter_max_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineparametervalue',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
