# Generated by Django 5.0.6 on 2024-06-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0009_alter_machineparametervalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
