# Generated by Django 5.0.6 on 2024-06-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0010_user_city_user_district_alter_user_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='machineparameter',
            unique_together={('name', 'unit_of_measurement', 'type')},
        ),
    ]
