# Generated by Django 5.0.6 on 2024-06-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0012_alter_machineparameter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.AddField(
            model_name='operation',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
