# Generated by Django 5.0.6 on 2024-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0013_remove_user_city_remove_user_district_operation_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineParameterValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_machine', models.CharField(max_length=16)),
                ('machine_name', models.CharField(max_length=40)),
                ('parameter_name', models.CharField(max_length=30)),
                ('unit_of_measurement', models.CharField(max_length=10)),
                ('old_value', models.FloatField(null=True)),
                ('new_value', models.FloatField(null=True)),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
