# Generated by Django 5.0.6 on 2024-06-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0014_machineparametervaluehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineparametervalue',
            name='updated_history_date',
            field=models.DateTimeField(null=True),
        ),
    ]
