# Generated by Django 5.0.6 on 2024-06-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0015_machineparametervalue_updated_history_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineparametervaluehistory',
            old_name='ip_machine',
            new_name='machine_ip',
        ),
    ]
