# Generated by Django 5.0.6 on 2024-06-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0016_rename_ip_machine_machineparametervaluehistory_machine_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineparametervaluehistory',
            name='activity_level',
            field=models.CharField(choices=[('Normal', 'Bình thường'), ('Warning', 'Cảnh báo'), ('Critical', 'Nguy hiểm')], default='Normal', max_length=10),
        ),
    ]
