# Generated by Django 5.0.6 on 2024-06-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0017_machineparametervaluehistory_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
